String base = 'http://192.168.109.221:6042';
// String base = 'http://128.199.199.164:6042';
String version = "v1";
String getAppInfoAPI = "/mobile_app/v1/info";
String loginPath = '/api/$version/user_login';
String registrationPath = '/api/$version/user_registration';
String startWorkPath = '/api/$version/attendance/start_work';
String dashBoardGetDataPath = '/api/$version/reports/dashboard';
String dashboardRouteInfo = "/api/$version/reports/dashboard/info";
String endWorkPath = '/api/$version/attendance/end_work';
String getDeliveryList = '/api/$version/delivery/v2/list';
String saveDeliveryList = '/api/$version/delivery/save';
String cashCollectionList = '/api/$version/cash_collection/v2/list';
String cashCollectionSave = '/api/$version/cash_collection/save';
String getCustomerList = '/api/$version/customer_location/v2/list';
String getCustomerDetailsByPartnerID =
    '/api/$version/customer_location/details';
String setCustomerLatLon =
    "/api/$version/customer_location/customer_location_update";
String conveyanceStart = "/api/$version/conveyance/start";
String conveyanceList = "/api/$version/conveyance/list";
String conveyanceEnd = "/api/$version/conveyance/end";
String conveyanceTransportMode = "/api/$version/conveyance/transport_modes";
String getOverdueList = "/api/$version/cash_collection/overdue/list";
String getOverdueListV2 = "/api/$version/overdue/list";
String collectOverdue = "/api/$version/overdue/collect";
String visitApiPath = "/api/$version/visit/create";
String reportsAPI = "/web_view/v1/reports";
String errorInfo = "/mobile_app/v1/error_info";
